# Generated by Django 4.0.3 on 2022-04-16 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название статьи', max_length=250, verbose_name='Название статьи')),
                ('category', models.CharField(help_text='Введите рубрику', max_length=150, verbose_name='Рубрика')),
                ('author', models.CharField(help_text='Укажите автора статьи', max_length=100, verbose_name='Автор')),
                ('date', models.DateField(help_text='Укажите дату создания статьи', verbose_name='Дата')),
                ('content', models.TextField(help_text='Напишите содержание статьи', verbose_name='Содержание')),
                ('conclusion', models.TextField(help_text='Напишите вывод статьи', verbose_name='Вывод')),
                ('image', models.ImageField(help_text='Загрузите одно изображение', null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите вашу электронную почту', max_length=254, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название журнала', max_length=250, verbose_name='Название журнала')),
                ('date', models.DateField(help_text='Укажите дату создания статьи', verbose_name='Дата')),
                ('image', models.ImageField(help_text='Загрузите одно изображение', null=True, upload_to='images/', verbose_name='Изображение')),
                ('file', models.FileField(help_text='Загрузите PDF журнала', null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF')),
                ('articles', models.ManyToManyField(help_text='Укажите статьи из этого журнала', to='mainapp.article', verbose_name='Статьи')),
            ],
        ),
    ]
