# Generated by Django 4.0.3 on 2022-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название рубрики', max_length=250, verbose_name='Название рубрики')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(help_text='Загрузите одно изображение', null=True, upload_to='images_article/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.ImageField(help_text='Загрузите одно изображение', null=True, upload_to='images_magazine/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(help_text='Укажите рубрики этого журнала', to='mainapp.category', verbose_name='Рубрики'),
        ),
    ]
