# Generated by Django 4.0.3 on 2022-11-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_article_title_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='count_article',
            field=models.IntegerField(default='0', help_text='Укажите количество статей', verbose_name='Количество статей'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='articles',
            field=models.ManyToManyField(default='1', help_text='Укажите статьи из этого журнала', to='mainapp.article', verbose_name='Статьи'),
        ),
    ]
