# Generated by Django 4.0.3 on 2022-11-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_magazine_count_article_alter_magazine_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='articles',
        ),
    ]
