# Generated by Django 4.0.3 on 2022-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_magazine_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='count_magazine',
            field=models.IntegerField(default='0', help_text='Укажите номер журнала', verbose_name='Номер выпуска'),
        ),
    ]
